name: khmer_date
description: Khmer Date is plugin help you to convert date time and number to Khmer
version: 1.0.3
homepage: https://github.com/RathaIct/KhmerDateDart
repository: https://github.com/RathaIct/KhmerDateDart
issue_tracker: https://github.com/RathaIct/KhmerDateDart/issues
maintainer: Hin Ratha (@RathaIct)
screenshots:
  - description: "Khmer date convertor"
    path: thumbnail.png
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  intl: ^0.19.0
