name: khmer_date
description: Khmer Date is plugin help you to convert date time and number to Khmer
version: 0.0.5
homepage: https://github.com/RathaIct/KhmerDateDart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
